export const Ideas = [
	{
		id: "1",
		name: "Ideas",
		link: "/ideas",
		image: "/ideas.jpeg",
		height: "h-20",
		width: "w-20",
	},
	{
		id: "2",
		name: "Current Affairs",
		link: "/current-affairs",
		image: "/current_affairs.jpeg",
		height: "h-20",
		width: "w-20",
	},
	{
		id: "3",
		name: "Liberalism",
		link: "/liberalism",
		image: "/liberalism.jpeg",
		height: "h-20",
		width: "w-20",
	},
	{
		id: "4",
		name: "Capitalism",
		link: "/capitalism",
		image: "/capitalism.jpeg",
		height: "h-20",
		width: "w-20",
	},
	{
		id: "5",
		name: "Comunism",
		link: "/comunism",
		image: "/comunism.jpeg",
		height: "h-20",
		width: "w-20",
	},
	{
		id: "6",
		name: "Socialism",
		link: "/socialism",
		image: "/socialism.jpeg",
		height: "h-20",
		width: "w-20",
	},
	{
		id: "7",
		name: "Freedom of Expression",
		link: "/freedom-of-expression",
		image: "/freedom_of_expression.jpeg",
		height: "h-20",
		width: "w-20",
	}
];